name: mall_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  connectivity_plus: ^6.1.3
  csv: ^6.0.0
  excel: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11


flutter:
  uses-material-design: true
